# Generated by Django 6.0.4 on 2026-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_normalize_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='kcal per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='grams', max_digits=5, null=True),
        ),
    ]
